version: '3'
services:
  bot:
    image: gdragon/throw-voice:${VERSION}
    env_file:
      - ${ENV:-sample}-b2.env
      - ${ENV:-sample}-bot.env
      - ${ENV:-sample}-rollbar.env
    environment:
      - JAVA_OPTIONS=--add-modules java.xml.bind
      - TZ=America/Los_Angeles
      - VERSION=${VERSION}
    volumes:
      - ./data:/app/data
    restart: on-failure:5
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '5'
  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  data:
    image: datasetteproject/datasette:0.25.1
    command: datasette -p 8001 -h 0.0.0.0 -m /mnt/metadata.json /mnt/settings.db
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./data/settings.db:/mnt/settings.db:ro
      - ${CONF:-./}metadata.json:/mnt/metadata.json
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '5'
  nginx:
    image: nginx:1.15-alpine
    command: /bin/sh -c "envsubst '$${BOT_HOST},$${DATA_HOST},$${DATA_WHITELIST_IP}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    environment:
      - BOT_HOST=${BOT_HOST:-localhost}
      - DATA_HOST=${DATA_HOST:-localhost}
      - DATA_WHITELIST_IP=${DATA_WHITELIST_IP:-127.0.0.1}
    volumes:
      - ${CONF:-./}nginx.conf:/etc/nginx/nginx.conf.template
    ports:
      - 80:80
    depends_on:
      - bot
      - data
      - portainer

volumes:
  portainer_data:
